package com.mclauncher.app.creation

import android.graphics.Bitmap
import android.graphics.BitmapFactory
import android.graphics.Canvas
import android.graphics.Color
import android.graphics.Paint
import com.mclauncher.model.ModLoader
import java.io.File
import java.util.Locale
import java.util.zip.ZipEntry
import java.util.zip.ZipOutputStream

data class GeneratedLocalProject(
    val directory: File,
    val id: String,
    val displayName: String,
    val mechanic: String,
    val verifiedFeature: Boolean
)

class LocalProjectGenerator(private val labRoot: File) {
    fun createModProject(
        prompt: String,
        target: LocalBuildTarget,
        attachments: List<LocalAttachment>
    ): GeneratedLocalProject {
        require(target.loader != ModLoader.VANILLA) { "Choose a Fabric, Quilt, Forge or NeoForge instance" }
        require(target.loaderVersion.isNotBlank()) { "The target instance has no loader version" }
        require(supportsVerifiedMod(prompt, target)) {
            "This request is not implemented by the local engine yet. No tiny placeholder JAR was created. " +
                "The current working mod capability is a grappling hook for Minecraft 1.20.1 on Fabric, Quilt, Forge or NeoForge."
        }
        val request = interpret(prompt, target)
        val stamp = System.currentTimeMillis().toString()
        val project = labRoot.resolve("projects/${request.modId}-$stamp").apply { mkdirs() }
        project.resolve("references").mkdirs()
        attachments.forEach { attachment ->
            File(attachment.localPath).takeIf(File::isFile)?.copyTo(
                project.resolve("references/${safeFileName(attachment.displayName)}"),
                overwrite = true
            )
        }
        project.resolve("MCL-SPECIFICATION.txt").writeText(
            buildString {
                appendLine("MCLauncher local project")
                appendLine("Target: ${target.loader.displayName} ${target.loaderVersion}, Minecraft ${target.minecraftVersion}")
                appendLine("Requested: $prompt")
                appendLine("Interpreted capability: ${request.mechanic}")
                if (attachments.isNotEmpty()) {
                    appendLine()
                    appendLine("Attachment inspection:")
                    attachments.forEach { appendLine("- ${it.displayName}: ${it.analysis}") }
                }
            }
        )
        project.resolve("LICENSE").writeText("Generated by the device owner with MCLauncher Creation Lab.\n")
        writeLoaderFiles(project, request, target)
        writeGrapplingResources(project, request, attachments)
        return GeneratedLocalProject(
            directory = project,
            id = request.modId,
            displayName = request.displayName,
            mechanic = request.mechanic,
            verifiedFeature = request.verifiedFeature
        )
    }

    fun assembleModJar(project: File, destination: File) {
        val resources = project.resolve("src/main/resources")
        require(resources.isDirectory) { "Generated project has no resources" }
        destination.parentFile?.mkdirs()
        val temporary = File(destination.parentFile, "${destination.name}.part").apply { delete() }
        try {
            ZipOutputStream(temporary.outputStream().buffered()).use { zip ->
                addTextEntry(zip, "META-INF/MANIFEST.MF", "Manifest-Version: 1.0\nCreated-By: MCLauncher Creation Lab\n\n")
                resources.walkTopDown().filter(File::isFile).sortedBy(File::getAbsolutePath).forEach { file ->
                    addFileEntry(zip, file, file.relativeTo(resources).invariantSeparatorsPath)
                }
                listOf("MCL-SPECIFICATION.txt", "LICENSE").forEach { name ->
                    project.resolve(name).takeIf(File::isFile)?.let { addFileEntry(zip, it, "META-INF/$name") }
                }
            }
            check(temporary.renameTo(destination)) { "Could not finish the local mod JAR" }
        } finally {
            temporary.delete()
        }
    }

    fun createShaderPack(
        prompt: String,
        minecraftVersion: String,
        attachments: List<LocalAttachment>
    ): Pair<File, File> {
        require(prompt.isNotBlank()) { "Describe the shader pack" }
        val stamp = System.currentTimeMillis().toString()
        val safe = safeId(prompt).take(32).ifBlank { "mcl_shader" }
        val project = labRoot.resolve("projects/$safe-$stamp").apply { mkdirs() }
        val shaders = project.resolve("shaders").apply { mkdirs() }
        val lower = prompt.lowercase(Locale.ROOT)
        val effect = when {
            "black and white" in lower || "grayscale" in lower || "monochrome" in lower -> ShaderEffect.GRAYSCALE
            "warm" in lower || "cinematic" in lower || "sunset" in lower -> ShaderEffect.WARM
            "vibrant" in lower || "saturated" in lower || "colorful" in lower -> ShaderEffect.VIBRANT
            "dark" in lower || "horror" in lower -> ShaderEffect.DARK
            else -> ShaderEffect.CLEAN
        }
        project.resolve("pack.mcmeta").writeText(
            """{"pack":{"pack_format":${packFormat(minecraftVersion)},"description":"${jsonEscape("MCLauncher local shader — ${effect.label}")}"}}"""
        )
        project.resolve("MCL-SPECIFICATION.txt").writeText(
            buildString {
                appendLine("Requested: $prompt")
                appendLine("Generated effect: ${effect.label}")
                appendLine("Target Minecraft: $minecraftVersion")
                attachments.forEach { appendLine("Attachment ${it.displayName}: ${it.analysis}") }
            }
        )
        shaders.resolve("final.vsh").writeText(FINAL_VERTEX_SHADER)
        shaders.resolve("final.fsh").writeText(finalFragmentShader(effect))
        shaders.resolve("shaders.properties").writeText("# Generated locally by MCLauncher\noldLighting=false\n")
        val outputDirectory = labRoot.resolve("outputs").apply { mkdirs() }
        val output = uniqueFile(outputDirectory, "$safe-$stamp.zip")
        zipDirectory(project, output)
        return project to output
    }

    private fun interpret(prompt: String, target: LocalBuildTarget): ModRequest {
        require(prompt.isNotBlank()) { "Describe the mod you want" }
        check(supportsVerifiedMod(prompt, target)) { "Unsupported mod request reached the verified generator" }
        return ModRequest(
            modId = "mcl_grappling_hook",
            displayName = "MCLauncher Grappling Hook",
            mechanic = "working grappling-hook item",
            verifiedFeature = true
        )
    }

    private fun supportsVerifiedMod(prompt: String, target: LocalBuildTarget): Boolean {
        val lower = prompt.lowercase(Locale.ROOT)
        return ("grappling" in lower || "grapple" in lower) && "hook" in lower &&
            target.minecraftVersion == "1.20.1"
    }

    private fun writeLoaderFiles(project: File, request: ModRequest, target: LocalBuildTarget) {
        val resources = project.resolve("src/main/resources").apply { mkdirs() }
        resources.resolve("pack.mcmeta").writeText(
            """{"pack":{"pack_format":${packFormat(target.minecraftVersion)},"description":"${jsonEscape(request.displayName)}"}}""" + "\n"
        )
        when (target.loader) {
            ModLoader.FABRIC -> resources.resolve("fabric.mod.json").writeText(fabricMetadata(request, target))
            ModLoader.QUILT -> resources.resolve("quilt.mod.json").writeText(quiltMetadata(request, target))
            ModLoader.FORGE -> resources.resolve("META-INF/mods.toml").apply { parentFile?.mkdirs() }
                .writeText(forgeMetadata(request, target, neo = false))
            ModLoader.NEOFORGE -> resources.resolve("META-INF/neoforge.mods.toml").apply { parentFile?.mkdirs() }
                .writeText(forgeMetadata(request, target, neo = true))
            ModLoader.VANILLA -> Unit
        }
    }

    private fun fabricMetadata(request: ModRequest, target: LocalBuildTarget): String = """
        {
          "schemaVersion": 1,
          "id": "${request.modId}",
          "version": "1.0.0",
          "name": "${jsonEscape(request.displayName)}",
          "description": "Data-driven mod assembled locally by MCLauncher. No API service or remote builder was used.",
          "environment": "*",
          "depends": { "fabricloader": ">=${target.loaderVersion}", "minecraft": "${target.minecraftVersion}" }
        }
    """.trimIndent() + "\n"

    private fun quiltMetadata(request: ModRequest, target: LocalBuildTarget): String = """
        {
          "schema_version": 1,
          "quilt_loader": {
            "group": "com.mclauncher.generated",
            "id": "${request.modId}",
            "version": "1.0.0",
            "metadata": {
              "name": "${jsonEscape(request.displayName)}",
              "description": "Generated locally by MCLauncher",
              "license": "ARR"
            },
            "intermediate_mappings": "net.fabricmc:intermediary",
            "depends": [
              { "id": "quilt_loader", "versions": ">=${target.loaderVersion}" },
              { "id": "minecraft", "versions": "${target.minecraftVersion}" }
            ]
          }
        }
    """.trimIndent() + "\n"

    private fun forgeMetadata(request: ModRequest, target: LocalBuildTarget, neo: Boolean): String {
        val loaderRange = if (neo) "[1,)" else "[47,)"
        val dependency = if (neo) "neoforge" else "forge"
        val loaderVersion = if (!neo) target.loaderVersion.removePrefix("${target.minecraftVersion}-") else target.loaderVersion
        return """
            modLoader="lowcodefml"
            loaderVersion="$loaderRange"
            license="All Rights Reserved"

            [[mods]]
            modId="${request.modId}"
            version="1.0.0"
            displayName="${tomlEscape(request.displayName)}"
            description='''Generated locally by MCLauncher. No API service or remote builder was used.'''

            [[dependencies.${request.modId}]]
            modId="$dependency"
            mandatory=true
            versionRange="[$loaderVersion,)"
            ordering="NONE"
            side="BOTH"

            [[dependencies.${request.modId}]]
            modId="minecraft"
            mandatory=true
            versionRange="[${target.minecraftVersion}]"
            ordering="NONE"
            side="BOTH"
        """.trimIndent() + "\n"
    }

    private fun writeGrapplingResources(project: File, request: ModRequest, attachments: List<LocalAttachment>) {
        val resources = project.resolve("src/main/resources")
        resources.resolve("assets/${request.modId}/lang/en_us.json").apply { parentFile?.mkdirs() }
            .writeText("{\"item.${request.modId}.grappling_hook\":\"Grappling Hook\"}\n")
        resources.resolve("assets/${request.modId}/models/item/grappling_hook.json").apply { parentFile?.mkdirs() }
            .writeText("{\"parent\":\"minecraft:item/handheld_rod\",\"textures\":{\"layer0\":\"${request.modId}:item/grappling_hook\"}}\n")
        resources.resolve("assets/${request.modId}/models/item/grappling_hook_cast.json").apply { parentFile?.mkdirs() }
            .writeText("{\"parent\":\"minecraft:item/handheld_rod\",\"textures\":{\"layer0\":\"${request.modId}:item/grappling_hook\"}}\n")
        resources.resolve("assets/minecraft/models/item/fishing_rod.json").apply { parentFile?.mkdirs() }
            .writeText(
                """{"parent":"minecraft:item/handheld_rod","textures":{"layer0":"minecraft:item/fishing_rod"},"overrides":[{"predicate":{"cast":1},"model":"minecraft:item/fishing_rod_cast"},{"predicate":{"custom_model_data":42001},"model":"${request.modId}:item/grappling_hook"},{"predicate":{"custom_model_data":42001,"cast":1},"model":"${request.modId}:item/grappling_hook_cast"}]}""" + "\n"
            )
        resources.resolve("data/${request.modId}/recipes/grappling_hook.json").apply { parentFile?.mkdirs() }
            .writeText(
                """{"type":"minecraft:crafting_shaped","pattern":[" II"," SI","S  "],"key":{"I":{"item":"minecraft:iron_ingot"},"S":{"item":"minecraft:string"}},"result":{"item":"minecraft:knowledge_book","count":1}}""" + "\n"
            )
        resources.resolve("data/${request.modId}/advancements/crafted_hook.json").apply { parentFile?.mkdirs() }
            .writeText(
                """{"criteria":{"crafted":{"trigger":"minecraft:recipe_crafted","conditions":{"recipe_id":"${request.modId}:grappling_hook"}}},"rewards":{"function":"${request.modId}:grant"}}""" + "\n"
            )
        resources.resolve("data/minecraft/tags/functions/load.json").apply { parentFile?.mkdirs() }
            .writeText("{\"values\":[\"${request.modId}:load\"]}\n")
        resources.resolve("data/minecraft/tags/functions/tick.json").apply { parentFile?.mkdirs() }
            .writeText("{\"values\":[\"${request.modId}:tick\"]}\n")
        val functions = resources.resolve("data/${request.modId}/functions").apply { mkdirs() }
        functions.resolve("load.mcfunction").writeText(
            "scoreboard objectives add mcl_grapple minecraft.used:minecraft.fishing_rod\n" +
                "scoreboard objectives add mcl_grapple_age dummy\n"
        )
        functions.resolve("grant.mcfunction").writeText(
            "clear @s minecraft:knowledge_book 1\n" +
                "give @s minecraft:fishing_rod{mcl_grapple:1b,CustomModelData:42001,display:{Name:'{\"text\":\"Grappling Hook\",\"color\":\"aqua\",\"italic\":false}',Lore:['{\"text\":\"Cast it, then fly toward the hook\",\"color\":\"gray\",\"italic\":false}']}} 1\n" +
                "advancement revoke @s only ${request.modId}:crafted_hook\n" +
                "playsound minecraft:entity.item.pickup player @s ~ ~ ~ 0.8 1.4\n"
        )
        functions.resolve("tick.mcfunction").writeText(
            "execute as @a[scores={mcl_grapple=1..},nbt={SelectedItem:{id:\"minecraft:fishing_rod\",tag:{mcl_grapple:1b}}}] at @s if entity @e[type=minecraft:fishing_bobber,distance=..48,sort=nearest,limit=1] run function ${request.modId}:start\n" +
                "scoreboard players set @a[scores={mcl_grapple=1..}] mcl_grapple 0\n" +
                "scoreboard players add @a[tag=mcl_grappling] mcl_grapple_age 1\n" +
                "execute as @a[tag=mcl_grappling] at @s if entity @e[type=minecraft:fishing_bobber,distance=..1.5,sort=nearest,limit=1] run function ${request.modId}:stop\n" +
                "execute as @a[tag=mcl_grappling,scores={mcl_grapple_age=2..80}] at @s if entity @e[type=minecraft:fishing_bobber,distance=1.5..48,sort=nearest,limit=1] facing entity @e[type=minecraft:fishing_bobber,distance=1.5..48,sort=nearest,limit=1] feet run tp @s ^ ^0.12 ^0.85\n" +
                "execute as @a[tag=mcl_grappling] at @s unless entity @e[type=minecraft:fishing_bobber,distance=..48,sort=nearest,limit=1] run function ${request.modId}:stop\n" +
                "execute as @a[tag=mcl_grappling,scores={mcl_grapple_age=81..}] run function ${request.modId}:stop\n"
        )
        functions.resolve("start.mcfunction").writeText(
            "tag @s add mcl_grappling\n" +
                "scoreboard players set @s mcl_grapple_age 0\n" +
                "playsound minecraft:entity.fishing_bobber.throw player @s ~ ~ ~ 0.9 1.15\n"
        )
        functions.resolve("stop.mcfunction").writeText(
            "tag @s remove mcl_grappling\n" +
                "scoreboard players set @s mcl_grapple_age 0\n"
        )
        val texture = resources.resolve("assets/${request.modId}/textures/item/grappling_hook.png").apply { parentFile?.mkdirs() }
        val image = attachments.firstOrNull { it.kind == AttachmentKind.IMAGE }
            ?.let { BitmapFactory.decodeFile(it.localPath) }
        if (image != null) {
            val scaled = Bitmap.createScaledBitmap(image, 16, 16, true)
            texture.outputStream().use { scaled.compress(Bitmap.CompressFormat.PNG, 100, it) }
            if (scaled !== image) scaled.recycle()
            image.recycle()
        } else {
            writeDefaultHookTexture(texture)
        }
    }

    private fun writeDefaultHookTexture(file: File) {
        val bitmap = Bitmap.createBitmap(16, 16, Bitmap.Config.ARGB_8888)
        val canvas = Canvas(bitmap)
        val paint = Paint().apply { isAntiAlias = false; style = Paint.Style.FILL }
        canvas.drawColor(Color.TRANSPARENT)
        paint.color = Color.rgb(205, 218, 224)
        listOf(11 to 2, 12 to 2, 10 to 3, 12 to 3, 9 to 4, 12 to 4, 8 to 5, 11 to 5, 8 to 6, 10 to 6, 8 to 7, 9 to 7)
            .forEach { (x, y) -> canvas.drawRect(x.toFloat(), y.toFloat(), x + 1f, y + 1f, paint) }
        paint.color = Color.rgb(130, 82, 48)
        for (i in 0..8) canvas.drawRect((7 - i / 2).toFloat(), (7 + i).toFloat(), (8 - i / 2).toFloat(), (8 + i).toFloat(), paint)
        file.outputStream().use { bitmap.compress(Bitmap.CompressFormat.PNG, 100, it) }
        bitmap.recycle()
    }

    private fun finalFragmentShader(effect: ShaderEffect): String {
        val transform = when (effect) {
            ShaderEffect.GRAYSCALE -> "float l = dot(color.rgb, vec3(0.299, 0.587, 0.114)); color.rgb = vec3(l);"
            ShaderEffect.WARM -> "color.rgb = vec3(color.r * 1.08, color.g * 1.01, color.b * 0.88);"
            ShaderEffect.VIBRANT -> "float l = dot(color.rgb, vec3(0.299, 0.587, 0.114)); color.rgb = mix(vec3(l), color.rgb, 1.35);"
            ShaderEffect.DARK -> "color.rgb = pow(color.rgb * 0.78, vec3(1.08));"
            ShaderEffect.CLEAN -> "color.rgb = color.rgb;"
        }
        return """
            #version 120
            uniform sampler2D colortex0;
            varying vec2 texcoord;
            void main() {
                vec4 color = texture2D(colortex0, texcoord);
                $transform
                gl_FragColor = color;
            }
        """.trimIndent() + "\n"
    }

    private fun zipDirectory(source: File, destination: File) {
        ZipOutputStream(destination.outputStream().buffered()).use { zip ->
            source.walkTopDown().filter(File::isFile).sortedBy(File::getAbsolutePath).forEach { file ->
                val relative = file.relativeTo(source).invariantSeparatorsPath
                zip.putNextEntry(ZipEntry(relative))
                file.inputStream().use { it.copyTo(zip) }
                zip.closeEntry()
            }
        }
    }

    private fun addTextEntry(zip: ZipOutputStream, name: String, value: String) {
        zip.putNextEntry(ZipEntry(name))
        zip.write(value.toByteArray(Charsets.UTF_8))
        zip.closeEntry()
    }

    private fun addFileEntry(zip: ZipOutputStream, file: File, name: String) {
        zip.putNextEntry(ZipEntry(name))
        file.inputStream().use { it.copyTo(zip) }
        zip.closeEntry()
    }

    private fun packFormat(version: String): Int = when {
        version.startsWith("26.") -> 75
        version.startsWith("1.21") -> 34
        version.startsWith("1.20.5") || version.startsWith("1.20.6") -> 32
        version.startsWith("1.20.3") || version.startsWith("1.20.4") -> 22
        else -> 15
    }

    private fun displayName(prompt: String): String = prompt.trim()
        .split(Regex("\\s+"))
        .take(7)
        .joinToString(" ")
        .take(64)
        .replaceFirstChar { if (it.isLowerCase()) it.titlecase(Locale.ROOT) else it.toString() }
        .ifBlank { "MCLauncher Generated Mod" }

    private fun safeId(value: String): String {
        val cleaned = value.lowercase(Locale.ROOT)
            .replace(Regex("[^a-z0-9_]+"), "_")
            .trim('_')
        return when {
            cleaned.length < 2 -> "mcl_generated_mod"
            cleaned.first() !in 'a'..'z' -> "mcl_$cleaned"
            else -> cleaned
        }
    }

    private fun safeFileName(value: String): String = value.replace(Regex("[\\\\/:*?\"<>|\\u0000-\\u001F]"), "_").take(120)
    private fun jsonEscape(value: String): String = value.replace("\\", "\\\\").replace("\"", "\\\"").replace("\n", "\\n")
    private fun tomlEscape(value: String): String = value.replace("\\", "\\\\").replace("\"", "\\\"").replace("\n", " ")

    private fun uniqueFile(parent: File, name: String): File {
        var file = parent.resolve(name)
        var number = 2
        while (file.exists()) {
            val base = name.substringBeforeLast('.', name)
            val extension = name.substringAfterLast('.', "").takeIf { name.contains('.') }.orEmpty()
            file = parent.resolve("$base-$number${if (extension.isBlank()) "" else ".$extension"}")
            number++
        }
        return file
    }

    private data class ModRequest(
        val modId: String,
        val displayName: String,
        val mechanic: String,
        val verifiedFeature: Boolean
    )

    private enum class ShaderEffect(val label: String) {
        CLEAN("clean pass-through"),
        GRAYSCALE("grayscale"),
        WARM("warm cinematic color"),
        VIBRANT("vibrant color"),
        DARK("dark atmosphere")
    }

    companion object {
        private val FINAL_VERTEX_SHADER = """
            #version 120
            varying vec2 texcoord;
            void main() {
                gl_Position = ftransform();
                texcoord = (gl_TextureMatrix[0] * gl_MultiTexCoord0).xy;
            }
        """.trimIndent() + "\n"
    }
}
